version: '3.8'

services:
  db:
    image: postgres:15
    container_name: smartstock-db
    environment:
      POSTGRES_DB: smartstock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresdemo
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: smartstock-backend:latest 
    pull_policy: never
    build:
      context: ./backend      
      network: host           
    container_name: smartstock-backend
    ports:
      - "6000:6000"
    environment:
      SERVER_PORT: 6000
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/smartstock
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresdemo
      JWT_SECRET_KEY: aVeryLongAndSuperSecureSecretKeyForMySmartStockApplication2025!@#$$
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
